server:
  port: 8080

spring:
  application:
    name: spring-boot-template
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.chaoxing.template
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  pattern:
    level: "%5p [traceId:%X{traceId:-}]"
  level:
    root: info
    com.chaoxing.template: debug
